project_id = "yxptlbdgdzbcpqkoqysc"

[functions.clavis]
verify_jwt = false

[functions.strongs]
verify_jwt = false

[functions.clavis-search]
verify_jwt = false

[functions.bible-text]
verify_jwt = false